import prophy

class ETraceType(prophy.enum):
    __metaclass__ = prophy.enum_generator
    _enumerators = [("ETraceType_InterfaceTrace", 0),
                    ("ETraceType_CellTrace", 1),
                    ("ETraceType_SubscriberTrace", 2)]

class ETraceReportingMode(prophy.enum):
    __metaclass__ = prophy.enum_generator
    _enumerators = [("ETraceReportingMode_OnlineNewSession", 0),
                    ("ETraceReportingMode_FileBasedNewSession", 1),
                    ("ETraceReportingMode_OnlineNewTrs", 2),
                    ("ETraceReportingMode_FileBasedNewTrs", 3)]

class ETraceDepth(prophy.enum):
    __metaclass__ = prophy.enum_generator
    _enumerators = [("ETraceDepth_Minimum", 0),
                    ("ETraceDepth_Medium", 1),
                    ("ETraceDepth_Maximum", 2)]

class ESTraceMsgsState(prophy.enum):
    __metaclass__ = prophy.enum_generator
    _enumerators = [("ESTraceMsgsState_all", 0),
                    ("ESTraceMsgsState_specific", 1),
                    ("ESTraceMsgsState_none", 2)]

class ELomStatus(prophy.enum):
    __metaclass__ = prophy.enum_generator
    _enumerators = [("ELomStatus_Ok", 0),
                    ("ELomStatus_Nok", 1),
                    ("ELomStatus_AlreadyRegistered", 2),
                    ("ELomStatus_UnknownObject", 3),
                    ("ELomStatus_NotEnoughMemory", 4),
                    ("ELomStatus_InvalidParameters", 5),
                    ("ELomStatus_MaxTraceSessionsReached", 6),
                    ("ELomStatus_TraceReferenceInUse", 7),
                    ("ELomStatus_FeatureNotSupported", 8),
                    ("ELomStatus_VendorSpecificTracingNotStarted", 9),
                    ("ELomStatus_ExtLinkConnectionFailure", 10)]

class EBrowserStatus(prophy.enum):
    __metaclass__ = prophy.enum_generator
    _enumerators = [("EBrowserStatus_OK", 0),
                    ("EBrowserStatus_NOK", 1),
                    ("EBrowserStatus_FeatureNotSupported", 2),
                    ("EBrowserStatus_MergedToOngoing", 3),
                    ("EBrowserStatus_InvalidParameter", 4),
                    ("EBrowserStatus_ApplicationRejected", 5)]

class EBrowserObjectName(prophy.enum):
    __metaclass__ = prophy.enum_generator
    _enumerators = [("EBrowserObjectName_Undefined", 0),
                    ("EBrowserObjectName_LteCell", 1000),
                    ("EBrowserObjectName_LteUser", 1001),
                    ("EBrowserObjectName_LteRadioBearer", 1002),
                    ("EBrowserObjectName_LteAccessBearerUser", 1003),
                    ("EBrowserObjectName_LtePlmn", 1004),
                    ("EBrowserObjectName_LteRepositoryL3", 1050),
                    ("EBrowserObjectName_LocalBrowserRepository", 1051),
                    ("EBrowserObjectName_LteMacTtiTrace", 1100),
                    ("EBrowserObjectName_LtePhyTtiTrace", 1101),
                    ("EBrowserObjectName_LteRxPower", 1102),
                    ("EBrowserObjectName_LteModulationConstellation", 1103),
                    ("EBrowserObjectName_LteRawBerNOTSUPPORTED", 1104),
                    ("EBrowserObjectName_LteSnr", 1105),
                    ("EBrowserObjectName_LteBerNOTSUPPORTED", 1106),
                    ("EBrowserObjectName_LteBler", 1107),
                    ("EBrowserObjectName_LtePuschProcessingDelayNOTSUPPORTED", 1108),
                    ("EBrowserObjectName_LtePuschAckNackMeasurementNOTSUPPORTED", 1109),
                    ("EBrowserObjectName_LtePrachPreambleMeasurement", 1110),
                    ("EBrowserObjectName_LtePrachProcessingDelay", 1111),
                    ("EBrowserObjectName_LtePrachLoadMeasurementNOTSUPPORTED", 1112),
                    ("EBrowserObjectName_LteSpectrumSnapshot", 1113),
                    ("EBrowserObjectName_LteHarqMeasurement", 1114),
                    ("EBrowserObjectName_LteTimeAdvanceMeasurement", 1115),
                    ("EBrowserObjectName_LtePucchSnr", 1116),
                    ("EBrowserObjectName_LtePucchRxPower", 1117),
                    ("EBrowserObjectName_LtePucchModulationConstellation", 1118),
                    ("EBrowserObjectName_LtePucchSpectrumSnapshotNOTSUPPORTED", 1119),
                    ("EBrowserObjectName_LtePucchControlData", 1120),
                    ("EBrowserObjectName_LtePuschControlDataNOTSUPPORTED", 1121),
                    ("EBrowserObjectName_LteSrs", 1122),
                    ("EBrowserObjectName_LteCounter", 1123),
                    ("EBrowserObjectName_LteStatisticalMeas", 1124),
                    ("EBrowserObjectName_LteMeasS1Tup", 1125),
                    ("EBrowserObjectName_LteMeasX2Tup", 1126),
                    ("EBrowserObjectName_LteMeasEnbTup", 1127),
                    ("EBrowserObjectName_LteMeasCellTup", 1128),
                    ("EBrowserObjectName_LteMeasUserTup", 1129),
                    ("EBrowserObjectName_LteMeasS1AP", 1130),
                    ("EBrowserObjectName_LteMeasCellLoad", 1131),
                    ("EBrowserObjectName_LteMeasRLC", 1132),
                    ("EBrowserObjectName_LteMeasPDCPData", 1133),
                    ("EBrowserObjectName_LteMeasTransportLoad", 1134),
                    ("EBrowserObjectName_LteMeasPowerAndQualityUL", 1135),
                    ("EBrowserObjectName_LteMeasEPSBearer", 1136),
                    ("EBrowserObjectName_LteMeasRadioBearer", 1137),
                    ("EBrowserObjectName_LteMeasRRC", 1138),
                    ("EBrowserObjectName_LteMeasIntraENBHandover", 1139),
                    ("EBrowserObjectName_LteMeasPowerAndQualityDL", 1140),
                    ("EBrowserObjectName_LteMeasCellResource", 1141),
                    ("EBrowserObjectName_LteMeasCellThroughput", 1142),
                    ("EBrowserObjectName_LteMeasUEState", 1143),
                    ("EBrowserObjectName_LteMeasInterENBHandover", 1144),
                    ("EBrowserObjectName_LteMeasNeighbourCellRelatedHandover", 1145),
                    ("EBrowserObjectName_LteMeasInterSystemHandover", 1146),
                    ("EBrowserObjectName_LteMeasGeneralHandover", 1147),
                    ("EBrowserObjectName_LteCellPhy", 1200),
                    ("EBrowserObjectName_LteCellPlmnPhy", 1201),
                    ("EBrowserObjectName_LteCellUlPhy", 1230),
                    ("EBrowserObjectName_LteCellDlPhy", 1270),
                    ("EBrowserObjectName_LteCellMac", 1301),
                    ("EBrowserObjectName_LteUserMac", 1302),
                    ("EBrowserObjectName_LteMacDlCqiCirTable", 1303),
                    ("EBrowserObjectName_LteMacDlPsCellParams", 1304),
                    ("EBrowserObjectName_LteCellMacTm", 1305),
                    ("EBrowserObjectName_LteUserMacTm", 1306),
                    ("EBrowserObjectName_LteMacUlBasicDelayWeightQ10Table", 1307),
                    ("EBrowserObjectName_LteMacDlDelayBasedPrioQ10Table", 1308),
                    ("EBrowserObjectName_LteMacCqi2AggregationTable", 1309),
                    ("EBrowserObjectName_LteMacActivityFactorTenthTable", 1310),
                    ("EBrowserObjectName_LteCellPlmnMac", 1311),
                    ("EBrowserObjectName_LteCellTup", 1401),
                    ("EBrowserObjectName_LteAccessBearerTup", 1402),
                    ("EBrowserObjectName_LteUserTup", 1403),
                    ("EBrowserObjectName_LteS1Tup", 1404),
                    ("EBrowserObjectName_LteX2Tup", 1405),
                    ("EBrowserObjectName_LteEnbTup", 1406),
                    ("EBrowserObjectName_LteCellPlmnTup", 1407),
                    ("EBrowserObjectName_LteCellL3", 1501),
                    ("EBrowserObjectName_LteUserL3", 1502),
                    ("EBrowserObjectName_LteRadioBearerL3", 1503),
                    ("EBrowserObjectName_LteEnbL3", 1504),
                    ("EBrowserObjectName_LteEnbL3Uec", 1505),
                    ("EBrowserObjectName_LteEnbL3Enbc", 1506),
                    ("EBrowserObjectName_LteCellInfo", 1601),
                    ("EBrowserObjectName_ClientLteBr", 1702),
                    ("EBrowserObjectName_MeasurementListLteBr", 1704),
                    ("EBrowserObjectName_LteCpu", 1801),
                    ("EBrowserObjectName_LteTraceS1Enbc", 1901),
                    ("EBrowserObjectName_LteTraceX2Enbc", 1902),
                    ("EBrowserObjectName_LteTraceS1Uec", 1903),
                    ("EBrowserObjectName_LteTraceX2Uec", 1904),
                    ("EBrowserObjectName_LteTraceDlCellL2", 1905),
                    ("EBrowserObjectName_LteTraceUlCellL2", 1906),
                    ("EBrowserObjectName_LteTraceS1", 1907),
                    ("EBrowserObjectName_LteTraceX2", 1908),
                    ("EBrowserObjectName_LteTraceRrcCellc", 1909),
                    ("EBrowserObjectName_LteTraceRrcUec", 1910),
                    ("EBrowserObjectName_LteTraceRrc", 1911),
                    ("EBrowserObjectName_CombinedMeasurements", 2001),
                    ("EBrowserObjectName_IPDataRateForUL", 2002),
                    ("EBrowserObjectName_IPDataRateForDL", 2003),
                    ("EBrowserObjectName_LteCellEnbc", 2101),
                    ("EBrowserObjectName_LteCellPlmnEnbc", 2102),
                    ("EBrowserObjectName_LteCellUec", 2201),
                    ("EBrowserObjectName_LteCellAdjUec", 2202),
                    ("EBrowserObjectName_LteCellAdjUtraUec", 2203),
                    ("EBrowserObjectName_LteCellAdjGsmUec", 2204),
                    ("EBrowserObjectName_LteCellPlmnUec", 2205),
                    ("EBrowserObjectName_LteCellCellc", 2301),
                    ("EBrowserObjectName_LteRawData", 2401),
                    ("EBrowserObjectName_ClientDct", 10001),
                    ("EBrowserObjectName_MeasurementListDct", 10002),
                    ("EBrowserObjectName_LteMacGenCell", 10003),
                    ("EBrowserObjectName_LteMacGenUser", 10004),
                    ("EBrowserObjectName_LteMacPsCell", 10005),
                    ("EBrowserObjectName_LteMacPsUser", 10006),
                    ("EBrowserObjectName_DctDlLevL1Cell", 10010),
                    ("EBrowserObjectName_DctDlPdcpSdu", 10011),
                    ("EBrowserObjectName_DctDlsch0", 10012),
                    ("EBrowserObjectName_DctDlsch1", 10013),
                    ("EBrowserObjectName_DctDlschData0", 10014),
                    ("EBrowserObjectName_DctDlschData1", 10015),
                    ("EBrowserObjectName_DctMacPduDump", 10016),
                    ("EBrowserObjectName_DctPersistentUlschData", 10017),
                    ("EBrowserObjectName_DctPersistentDlschData", 10018),
                    ("EBrowserObjectName_DctRlcAmPdu", 10019),
                    ("EBrowserObjectName_DctRlcUmPdu", 10020),
                    ("EBrowserObjectName_DctUlLevL1Cell", 10021),
                    ("EBrowserObjectName_DctUlLevL1Ue", 10022),
                    ("EBrowserObjectName_DctUlPdpcPdu", 10023),
                    ("EBrowserObjectName_DctUlsch0", 10024),
                    ("EBrowserObjectName_DctUlsch1", 10025),
                    ("EBrowserObjectName_DctUlschData0", 10026),
                    ("EBrowserObjectName_DctUlschData1", 10027),
                    ("EBrowserObjectName_DctDlschData2", 10028),
                    ("EBrowserObjectName_DctDlRlcAmPdu", 10029),
                    ("EBrowserObjectName_DctDlRlcUmPdu", 10030),
                    ("EBrowserObjectName_DctDlMacPduDump", 10031),
                    ("EBrowserObjectName_DctUlMacPduDump", 10032),
                    ("EBrowserObjectName_DctUlRlcAmPdu", 10033),
                    ("EBrowserObjectName_DctUlRlcUmPdu", 10034),
                    ("EBrowserObjectName_DctUci", 10035),
                    ("EBrowserObjectName_DctRa", 10036),
                    ("EBrowserObjectName_DctUlsch1Tm", 10037),
                    ("EBrowserObjectName_DctDlsch1Tm", 10038),
                    ("EBrowserObjectName_DctDlschData2Tm", 10039),
                    ("EBrowserObjectName_DctUlschData1Tm", 10040),
                    ("EBrowserObjectName_DctUlschData0Tm", 10041),
                    ("EBrowserObjectName_DctUlLevL1CellTm", 10042),
                    ("EBrowserObjectName_DctDlschData3", 10043),
                    ("EBrowserObjectName_DctUlschData2", 10044),
                    ("EBrowserObjectName_DctUlschData2Tm", 10045),
                    ("EBrowserObjectName_DctDlRlcSdu", 10046),
                    ("EBrowserObjectName_LteCpuLoad", 10047),
                    ("EBrowserObjectName_LteCycleCpuLoad", 10048),
                    ("EBrowserObjectName_Last", 10049)]
