import aprot

class ECause(aprot.enum):
	__metaclass__ = aprot.enum_generator
	_enumerators = [('ECause_ReconfigurationCFNNotElapsed',28),
	 			    ('ECause_NotActivated_Allocated',23),
	 			    ('ECause_OverlappingDLCMSequences',36),
	 			    ('ECause_InvalidCMSettings',25),
	 			    ('ECause_NoCause',0),
	 			    ('ECause_HardwareOverload',2),
	 			    ('ECause_ParallelTransactionNotSupported',14),
	 			    ('ECause_OAMIntervention',3),
	 			    ('ECause_AbstractSyntaxError_Reject',17),
	 			    ('ECause_UnspecifiedCell',8),
	 			    ('ECause_AbstractSyntaxError_Notify',18),
	 			    ('ECause_MessageNotCompatibleWithReceiverState',21),
	 			    ('ECause_ServiceOrOptionNotAvailable_Implemented_Unspecified',15),
	 			    ('ECause_NotEnoughResources',10),
	 			    ('ECause_ProtocolError_Unspecified',29),
	 			    ('ECause_CellRestartNotAllowed',4),
	 			    ('ECause_SemanticError',20),
	 			    ('ECause_TransferSyntaxError',16),
	 			    ('ECause_EquipmentFailure',7),
	 			    ('ECause_ThreeLastULFramesCompressed',34),
	 			    ('ECause_ParameterOutOfRange',24),
	 			    ('ECause_NormalEvent_Unspecified',6),
	 			    ('ECause_HWResourceNotAvailable',9),
	 			    ('ECause_AlreadyActivated_Allocated',22),
	 			    ('ECause_NotEnoughULSlotsBetweenGaps',35),
	 			    ('ECause_BSCapabilityFailure',12),
	 			    ('ECause_MeasurementNotSupportedForTheObject',30),
	 			    ('ECause_NoCapabilityToCombineIndicatedCells',13),
	 			    ('ECause_OverlappingULCMSequences',33),
	 			    ('ECause_CellNotAvailable',32),
	 			    ('ECause_ParallelTransactionNotAllowed',26),
	 			    ('ECause_NotEnoughDLSlotsBetweenGaps',38),
	 			    ('ECause_AbstractSyntaxError_FalselyConstructedMessage',19),
	 			    ('ECause_ResourceUnavailable_Unspecified',11),
	 			    ('ECause_BCCHSchedulingError',27),
	 			    ('ECause_SignalingBearerOverflow',5),
	 			    ('ECause_ThreeLastDLFramesCompressed',37),
	 			    ('ECause_MeasurementTemporarilyNotAvailable',31),
	 			    ('ECause_SynchronizationFailure',1)]