import aprot

class ERadSwDomain(aprot.enum):
	__metaclass__ = aprot.enum_generator
	_enumerators = [('ERadSwDomain_Oam',25),
	 			    ('ERadSwDomain_LteMacPsCommon',32),
	 			    ('ERadSwDomain_LteMac',10),
	 			    ('ERadSwDomain_Dft',3),
	 			    ('ERadSwDomain_LteDlPhy',23),
	 			    ('ERadSwDomain_LteTupUl',13),
	 			    ('ERadSwDomain_Telecom',4),
	 			    ('ERadSwDomain_LteRrom',18),
	 			    ('ERadSwDomain_DSPRake',7),
	 			    ('ERadSwDomain_LteMacTddPs',29),
	 			    ('ERadSwDomain_LteCommon',16),
	 			    ('ERadSwDomain_DspHwApi',27),
	 			    ('ERadSwDomain_DSPMac_hs',8),
	 			    ('ERadSwDomain_LteMacDcmPs',31),
	 			    ('ERadSwDomain_LteLom',20),
	 			    ('ERadSwDomain_Legacy',0),
	 			    ('ERadSwDomain_Last',34),
	 			    ('ERadSwDomain_LteMacFddPs',30),
	 			    ('ERadSwDomain_Ccs',1),
	 			    ('ERadSwDomain_LteSmc',24),
	 			    ('ERadSwDomain_LteUlPhy',22),
	 			    ('ERadSwDomain_LteCellC',15),
	 			    ('ERadSwDomain_LOM',28),
	 			    ('ERadSwDomain_LteEnbc',17),
	 			    ('ERadSwDomain_HwApi',2),
	 			    ('ERadSwDomain_LteMacUl',11),
	 			    ('ERadSwDomain_LteMacDl',12),
	 			    ('ERadSwDomain_LteUec',19),
	 			    ('ERadSwDomain_BM',33),
	 			    ('ERadSwDomain_Trs',26),
	 			    ('ERadSwDomain_DSPCodec',6),
	 			    ('ERadSwDomain_DSPHsupaL2',9),
	 			    ('ERadSwDomain_TUP',5),
	 			    ('ERadSwDomain_LteTupDl',14),
	 			    ('ERadSwDomain_LteTupC',21)]