import aprot

class EStatus(aprot.enum):
	__metaclass__ = aprot.enum_generator
	_enumerators = [('EStatus_CellIdAlreadyInUse',301),
	 			    ('EStatus_WTR_ChannelIsBarred',0x9003),
	 			    ('EStatus_NoWspResources',307),
	 			    ('EStatus_BB_NotActivated',0x8002),
	 			    ('EStatus_FeatureAlreadyActivated',309),
	 			    ('EStatus_UserInSync',2),
	 			    ('EStatus_UnknownAtmMcu',312),
	 			    ('EStatus_UnknownAal2Id',314),
	 			    ('EStatus_ResourceUnavailable',401),
	 			    ('EStatus_LinkOutOfService',304),
	 			    ('EStatus_NoError',0),
	 			    ('EStatus_NoResponseFromCoPro',308),
	 			    ('EStatus_CellNotConfigured',306),
	 			    ('EStatus_ErroneusCellState',305),
	 			    ('EStatus_UnknownCellID',303),
	 			    ('EStatus_Timeout',5),
	 			    ('EStatus_PseudoLoadAdjusted',311),
	 			    ('EStatus_Active',8),
	 			    ('EStatus_UndefinedError',1),
	 			    ('EStatus_WspcPpcLoadLimitAdjusted',310),
	 			    ('EStatus_NoSpaceForCell',302),
	 			    ('EStatus_Initialized',6),
	 			    ('EStatus_ErroneusValueInMessage',300),
	 			    ('EStatus_ParallelOperationOngoing',10),
	 			    ('EStatus_InvalidParam',4),
	 			    ('EStatus_RbusSynchronizationFailure',400),
	 			    ('EStatus_InActive',9),
	 			    ('EStatus_WTR_NotInitialised',0x9001),
	 			    ('EStatus_UnknownWspId',313),
	 			    ('EStatus_UserOutOfSync',3),
	 			    ('EStatus_NotInitialized',7),
	 			    ('EStatus_WTR_InvalidFrequencyBand',0x9002),
	 			    ('EStatus_BB_AlreadyActivated',0x8001)]