import sys
from waflib.TaskGen import extension
from waflib.Task import Task
from waflib.Tools import waf_unit_test

def options(ctx):
    ctx.load('compiler_cxx python waf_unit_test')

def configure(ctx):
    pass

def configure_test(ctx):
    ctx.load('compiler_cxx python waf_unit_test')
    ctx.check(lib = 'gtest gmock')
    ctx.check_python_module('ply')
    ctx.check_python_module('clang')
    ctx.env.CXXFLAGS = ['-g', '-O0', '-Wall', '-std=gnu++0x']

def build(ctx):
    for dir in ctx.path.ant_glob('include/**/*', dir=True, src=False):
        ctx.install_files('${{PREFIX}}/{}'.format(dir.nice_path()), dir.ant_glob('*'))

def test(ctx):
    os_lib = []
    if 'linux' in sys.platform:
        os_lib += ['pthread']

    ctx.objects(
        features = 'cxx',
        includes = ['include', 'test'],
        export_includes = ['include', 'test'],
        source = ctx.path.ant_glob('test/*.prophy'),
        target = 'prophy_codecs',
        install_path = None
    )

    ctx.program(
        features = 'test',
        target = 'test_prophy',
        source = ctx.path.ant_glob('test/**.cpp'),
        use = ['prophy_codecs'],
        lib = ['gtest', 'gmock'] + os_lib,
        install_path = None
    )

    ctx.add_post_fun(waf_unit_test.summary)
    ctx.add_post_fun(waf_unit_test.set_exit_code)

run_str = 'PYTHONPATH=${bld.path.parent.abspath()} python -m prophyc --%s ${TGT[0].parent.abspath()} ${SRC[0].abspath()}'

class prophyc_cpp_full(Task):
    run_str = run_str % "cpp_full_out"
    shell = True

class prophyc_cpp(Task):
    run_str = run_str % "cpp_out"
    shell = True

@extension('.prophy')
def process_prophy(self, node):
    tsk_full = self.create_task('prophyc_cpp_full', [node], node.change_ext('.ppf.cpp'))
    tsk = self.create_task('prophyc_cpp', [node], node.change_ext('.pp.cpp'))
    self.source.extend(tsk_full.outputs + tsk.outputs)

from waflib.Configure import ConfigurationContext
from waflib.Build import BuildContext

class ConfigureTestContext(ConfigurationContext):
    cmd = 'configure_test'
    fun = 'configure_test'

class TestContext(BuildContext):
    cmd = 'test'
    fun = 'test'

